package com.humber.parenthood.eat_in_layout;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;

public class KitchenItems {
    public static ArrayList<String> getItems() {
        ArrayList<String> items = new ArrayList<>();
        items.add("Alcohol");
        items.add("Bagels");
        items.add("Barbecue sauce");
        items.add("Bottled water");
        items.add("Bouillon cubes");
        items.add("Bread");
        items.add("Brownies");
        items.add("Butter");
        items.add("Cakes (e.g., chocolate cake, vanilla cake)");
        items.add("Candy");
        items.add("Canned beans");
        items.add("Canned fish (e.g., tuna, salmon, sardines)");
        items.add("Canned fruits");
        items.add("Canned meat (e.g., tuna, chicken)");
        items.add("Canned pasta");
        items.add("Canned soup");
        items.add("Canned tomatoes");
        items.add("Canned vegetables");
        items.add("Cereal");
        items.add("Cheese");
        items.add("Chips");
        items.add("Chocolate");
        items.add("Coconut milk");
        items.add("Coffee beans");
        items.add("Condensed milk");
        items.add("Condiments");
        items.add("Cookies");
        items.add("Cooking oil");
        items.add("Cottage cheese");
        items.add("Crackers");
        items.add("Cream cheese");
        items.add("Croissants");
        items.add("Cupcakes");
        items.add("Dinner rolls");
        items.add("Donuts");
        items.add("Dried fruits");
        items.add("Eggs");
        items.add("Evaporated milk");
        items.add("Gum");
        items.add("Hamburger buns");
        items.add("Honey");
        items.add("Hot dog buns");
        items.add("Hot sauce");
        items.add("Ice cream");
        items.add("Instant coffee");
        items.add("Instant noodles");
        items.add("Jam");
        items.add("Juice");
        items.add("Maple syrup");
        items.add("Margarine");
        items.add("Mayonnaise");
        items.add("Milk");
        items.add("Mints");
        items.add("Muffins");
        items.add("Naan");
        items.add("Nuts");
        items.add("Olives");
        items.add("Pasta sauce");
        items.add("Pasta");
        items.add("Peanut butter");
        items.add("Pickles");
        items.add("Pita bread");
        items.add("Pretzels");
        items.add("Rice cakes");
        items.add("Rice");
        items.add("Salad dressing");
        items.add("Salsa");
        items.add("Seeds");
        items.add("Soup base");
        items.add("Soup mix");
        items.add("Sour cream");
        items.add("Soy sauce");
        items.add("Stock");
        items.add("Tea");
        items.add("Tomato paste");
        items.add("Tomato sauce");
        items.add("Tortillas");
        items.add("Vinegar");
        items.add("Whipped cream");
        items.add("Worcestershire sauce");
        items.add("Yogurt");

        Collections.sort(items);

        return items;
    }
}

